import './global.scss'
import Footer from '@/components/Footer/Footer'
import React from 'react'
import Header from '@/components/Header/Header'
import TabBar from '@/components/UI/TabBar/TabBar'
import {Metadata} from 'next'
import {Providers} from '@/redux/Provider'
import AuthWindow from '@/components/AuthWindow/AuthWindow'


export const metadata: Metadata = {
    title: 'Онлайн-кинотеатр Иви - фильмы, сериалы и мультфильмы смотреть онлайн бесплатно в хорошем качестве',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {


    return (
        <html lang='en'>
        <body>
        <Providers>
            <Header/>
            <AuthWindow/>
            {/*<Auth/>*/}
            <main>
                {children}
            </main>
            <TabBar/>
            <Footer/>
        </Providers>
        </body>
        </html>
    )
}
