import './global.scss'
import Footer from '@/components/Footer/Footer'
import React from 'react'
import Header from '@/components/Header/Header'
import TabBar from '@/components/UI/TabBar/TabBar'
import {Metadata} from 'next'
import {Providers} from '@/redux/Provider'
import Auth from '@/components/Auth/Auth'
import ProviderAuth from '@/app/Provider'


export const metadata: Metadata = {
    title: 'Онлайн-кинотеатр Иви - фильмы, сериалы и мультфильмы смотреть онлайн бесплатно в хорошем качестве',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {


    return (
        <html lang='en'>
        <body>
        <ProviderAuth>
            <Providers>
                <Header/>
                <Auth/>
                {/*<Auth/>*/}
                <main>
                    {children}
                </main>
                <TabBar/>
                <Footer/>
            </Providers>
        </ProviderAuth>
        </body>
        </html>
    )
}
