import FilterFilms from '@/components/FilterFilms/FilterFilms'

import {Metadata} from 'next'

import styles from './movies.module.scss'
import FilmsList from '@/components/FilmsList/FilmsList'


export const metadata: Metadata = {
    title: 'Смотреть фильмы онлайн бесплатно в хорошем HD качестве и без регистрации. Удобный просмотр онлайн фильмов на ivi.ru',
    description: 'Generated by Next.js',
}

// async function getCardFilms(e = 1) {
//     try {
//         const response = await fetch(
//             `http://localhost:12120/api/films/part/${e}`,
//             // {next: {revalidate: 100}}
//         )
//         return response.json()
//     } catch (error) {
//         console.log(error)
//     }
// }


const Movies = async () => {

    // const posts = await getCardFilms()

    return (
        <div className={styles.container}>
            <div className={styles.wrapper}>
                <FilterFilms/>
                <FilmsList/>
                {/*{posts && posts.map(item => <p style={{color: 'white'}} key={item.id}>{item.nameRU}</p>)}*/}
                {/*<button className={styles.movies__btn} >Показать еще</button>*/}
            </div>
        </div>
    )
}

export default Movies