import './global.scss'
import Footer from '@/components/Footer/Footer'
import React from 'react'
import Header from '@/components/Header/Header'
import TabBar from '@/components/UI/TabBar/TabBar'
import {Metadata} from 'next'
import {Providers} from '@/redux/Provider'
import Auth from '@/components/Auth/Auth'
import Provider from '@/app/[locale]/Provider'
import {useLocale} from 'next-intl'
import {notFound} from 'next/navigation'
import {NextIntlClientProvider} from 'next-intl'


export const metadata: Metadata = {
    title: 'Онлайн-кинотеатр Иви - фильмы, сериалы и мультфильмы смотреть онлайн бесплатно в хорошем качестве',
    description: 'Generated by Next.js',
}

export function generateStaticParams() {
    return [{locale: 'en'}, {locale: 'de'}]
}

export default async function RootLayout({children, params: {locale}}){
//                                        : {
//     children: React.ReactNode
//     // params : string
// })

    let messages
    try {
        messages = (await import(`../../messages/${locale}.json`)).default
    } catch (error) {
        notFound()
    }


    return (
        <html lang={locale}>
        <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
        <Provider>
            <Providers>
                <Header/>
                <Auth/>
                <main>
                    {children}
                </main>
                <TabBar/>
                <Footer/>
            </Providers>
        </Provider>
        </NextIntlClientProvider>
        </body>
        </html>
    )
}
